[package]
name = "atm-daemon"
autolib = false
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "ATM daemon runtime crate scaffold."
repository.workspace = true
homepage.workspace = true

[dependencies]
tokio.workspace = true
atm-core = { workspace = true, features = ["test-utils"] }
atm-daemon-bootstrap.workspace = true
