#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys

from phase_ad_suite import SuiteRowSpec, run_suite


POST_SEND_ROWS = [
    SuiteRowSpec(
        id="AD29-POSTSEND-EXTERNAL-001",
        flow="external post-send hook success suppresses built-in fallback while preserving durable send success",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "send::hook::tests::external_post_send_hook_takes_precedence_over_built_in_nudge",
                "--",
                "--exact",
            ],
        ],
        pass_note="external post-send hook success keeps the built-in nudge path inactive while durable send success remains intact",
    ),
    SuiteRowSpec(
        id="AD29-POSTSEND-PARTIAL-001",
        flow="mixed post-send hook outcomes preserve durable delivery while surfacing sender-visible warnings",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "send::hook::tests::mixed_success_hook_accounting_preserves_delivery_and_warning",
                "--",
                "--exact",
            ],
        ],
        pass_note="mixed hook accounting preserves durable delivery success and retains a sender-visible warning for failed matches",
    ),
    SuiteRowSpec(
        id="AD29-POSTSEND-BUILTIN-001",
        flow="built-in fallback covers both tmux and graft recipients when no external hook matches",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "send::hook::tests::built_in_fallback_dispatches_local_tmux_through_emitter",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "send::hook::tests::graft_fallback_dispatches_through_emitter_without_tmux_fields",
                "--",
                "--exact",
            ],
        ],
        pass_note="built-in fallback stays honest for both tmux-backed and graft-backed recipients when no external hook matches",
    ),
    SuiteRowSpec(
        id="AD29-POSTSEND-RESET-001",
        flow="deleting a prior override row restores the built-in default template path",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "atm-storage-rusqlite",
                "nudge_template_override_store::tests::sqlite_override_store_returns_none_after_override_row_is_deleted",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "send::nudge_template::tests::resolve_template_body_uses_default_when_no_override_exists",
                "--",
                "--exact",
            ],
        ],
        pass_note="removing a stored override row re-exposes the built-in default template instead of leaving an implicit disabled state behind",
    ),
    SuiteRowSpec(
        id="AD29-POSTSEND-DISABLE-001",
        flow="explicitly disabled built-in template state skips local post-send delivery cleanly",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::internal_nudge::tests::internal_nudge_run_skips_delivery_when_template_is_explicitly_disabled",
                "--",
                "--exact",
            ],
        ],
        pass_note="the explicit disabled-template state becomes a documented no-delivery path instead of an accidental empty-string side effect",
    ),
]

THOROUGH_ROWS = [
    SuiteRowSpec(
        id="AD11-CMD-SEND-001",
        flow="send command preserves caller-context ownership across environment and explicit override paths",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "build_request_uses_environment_when_overrides_are_absent",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "build_request_prefers_cli_overrides_over_environment",
            ],
        ],
        pass_note="send stays bound to the shared caller-context contract across environment and explicit override paths",
    ),
    SuiteRowSpec(
        id="AD11-CMD-READ-001",
        flow="read command preserves caller-context ownership across environment and explicit override paths",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "build_query_uses_environment_when_overrides_are_absent",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "build_query_prefers_cli_overrides_over_environment",
            ],
        ],
        pass_note="read stays bound to the shared caller-context contract across environment and explicit override paths",
    ),
    SuiteRowSpec(
        id="AD11-CMD-ACK-001",
        flow="ack command preserves caller-context ownership across environment and explicit override paths",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::ack::tests::build_request_uses_environment_when_overrides_are_absent",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::ack::tests::build_request_prefers_cli_overrides_over_environment",
                "--",
                "--exact",
            ],
        ],
        pass_note="ack stays bound to the shared caller-context contract across environment and explicit override paths",
    ),
    SuiteRowSpec(
        id="AD11-CMD-LIST-001",
        flow="list command preserves retained filters while keeping caller-context ownership explicit",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::list::tests::build_query_preserves_limit_and_filters",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::list::tests::build_query_uses_environment_when_overrides_are_absent",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::list::tests::build_query_prefers_cli_overrides_over_environment",
                "--",
                "--exact",
            ],
        ],
        pass_note="list preserves retained filters while staying bound to explicit caller-context ownership",
    ),
    SuiteRowSpec(
        id="AD11-CMD-CLEAR-001",
        flow="clear command preserves caller-context ownership across environment and explicit override paths",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::clear::tests::build_query_uses_environment_when_overrides_are_absent",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::clear::tests::build_query_prefers_cli_overrides_over_environment",
                "--",
                "--exact",
            ],
        ],
        pass_note="clear stays bound to the shared caller-context contract across environment and explicit override paths",
    ),
    SuiteRowSpec(
        id="AD11-CMD-LOG-001",
        flow="log command remains daemon-independent with caller-context enforcement at the CLI boundary",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::log::tests::run_snapshot_reads_real_retained_log_without_daemon",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::log::tests::run_snapshot_fails_without_caller_context",
                "--",
                "--exact",
            ],
        ],
        pass_note="log remains daemon-independent and still fails locally when caller context is unavailable",
    ),
    SuiteRowSpec(
        id="AD11-CMD-MEMBERS-001",
        flow="members command remains daemon-independent while preserving explicit team override handling",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::members::tests::run_lists_member_roster_without_daemon",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::members::tests::build_query_preserves_team_override",
                "--",
                "--exact",
            ],
        ],
        pass_note="members remains daemon-independent while preserving retained caller-team semantics",
    ),
    SuiteRowSpec(
        id="AD11-CMD-TEAMS-001",
        flow="teams list command remains daemon-independent on the retained CLI surface",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::teams::tests::teams_run_lists_discovered_teams_without_daemon",
                "--",
                "--exact",
            ],
        ],
        pass_note="teams list remains daemon-independent on the retained CLI surface",
    ),
    SuiteRowSpec(
        id="AD11-CMD-TEAMS-ADD-MEMBER-001",
        flow="teams add-member preserves the retained home-dir payload contract",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::teams::tests::add_member_build_request_preserves_atm_and_member_home_dirs",
                "--",
                "--exact",
            ],
        ],
        pass_note="teams add-member preserves the retained home-dir payload contract",
    ),
    SuiteRowSpec(
        id="AD11-CMD-TEAMS-UPDATE-MEMBER-001",
        flow="teams update-member preserves caller context and fails locally when mandatory caller context is missing",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::teams::tests::update_member_build_request_preserves_target_and_caller_context",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::teams::tests::update_member_requires_identity_from_environment",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::teams::tests::update_member_requires_team_from_environment_not_positional_target",
                "--",
                "--exact",
            ],
        ],
        pass_note="teams update-member preserves caller context and still fails locally when mandatory caller context is missing",
    ),
    SuiteRowSpec(
        id="AD11-CMD-TEAMS-BACKUP-001",
        flow="teams backup preserves retained team scoping and remains daemon-independent in dry-run execution",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::teams::tests::backup_build_request_preserves_team",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::teams::tests::backup_and_restore_dry_run_execute_without_daemon",
                "--",
                "--exact",
            ],
        ],
        pass_note="teams backup preserves retained team scoping and remains daemon-independent in dry-run execution",
    ),
    SuiteRowSpec(
        id="AD11-CMD-TEAMS-RESTORE-001",
        flow="teams restore preserves retained path and dry-run behavior without requiring the daemon",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::teams::tests::restore_build_request_preserves_from_path_and_dry_run",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::teams::tests::backup_and_restore_dry_run_execute_without_daemon",
                "--",
                "--exact",
            ],
        ],
        pass_note="teams restore preserves retained path and dry-run behavior without requiring the daemon",
    ),
    SuiteRowSpec(
        id="AD11-CMD-DOCTOR-001",
        flow="doctor remains identity-free while preserving optional team scoping and the direct local path",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::doctor::tests::build_query_preserves_team_override",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail",
                "commands::doctor::tests::execute_runs_direct_local_doctor_path",
                "--",
                "--exact",
            ],
        ],
        pass_note="doctor remains identity-free while preserving optional team scoping and the direct local path",
    ),
    SuiteRowSpec(
        id="AD11-POSTSEND-LOCAL-TMUX-001",
        flow="local tmux post-send requires and uses authoritative pane metadata",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "send::hook::tests::local_tmux_post_send_emitter_requires_authoritative_pane_id",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "send::hook::tests::local_tmux_post_send_emitter_uses_authoritative_pane_id",
                "--",
                "--exact",
            ],
        ],
        pass_note="local tmux post-send remains bound to authoritative roster pane metadata",
    ),
    SuiteRowSpec(
        id="AD11-POSTSEND-WARNING-001",
        flow="sender-visible warning fallback survives failed post-send emission",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "send::hook::tests::local_tmux_post_send_emitter_uses_authoritative_pane_id",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "send::tests::send_append_failure_routes_to_post_send_hook_fallback",
                "--",
                "--exact",
            ],
        ],
        pass_note="failed post-send emission still degrades into a sender-visible warning after durable send success",
    ),
    SuiteRowSpec(
        id="AD11-ROSTER-REPAIR-001",
        flow="fixture evidence preserves repaired pane metadata through team-admin and doctor projections",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "team_admin::tests::update_member_repairs_existing_roster_metadata_and_projects_config",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "doctor::tests::run_doctor_reports_pane_and_home_dir_drift_from_roster_truth",
                "--",
                "--exact",
            ],
        ],
        pass_note="fixture-backed smoke evidence proves pane repair survives the accepted team-admin and doctor projection paths",
    ),
    SuiteRowSpec(
        id="AD11-XREPO-001",
        flow="sender roster home_dir governs post-send config lookup across repos",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "send::hook::tests::sender_config_root_prefers_home_dir_and_falls_back_to_cwd",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "send::hook::tests::load_post_send_config_uses_sender_roster_metadata_not_caller_cwd",
                "--",
                "--exact",
            ],
        ],
        pass_note="post-send config discovery remains anchored to sender roster metadata rather than ambient caller cwd, preserving cross-repo local-send behavior",
    ),
    SuiteRowSpec(
        id="AD11-GRAFT-001",
        flow="graft-backed post-send uses a direct same-host receiver socket with typed warning fallback",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "atm-daemon",
                "tests_post_send_graft_warning::dispatcher_send_delivers_direct_graft_nudge_without_warning",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "atm-daemon",
                "tests_post_send_graft_warning::dispatcher_send_surfaces_typed_warning_when_graft_receiver_path_is_unavailable",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "atm-daemon",
                "tests_post_send_graft_warning::dispatcher_ack_surfaces_typed_warning_when_graft_reply_target_is_unavailable",
                "--",
                "--exact",
            ],
        ],
        pass_note="the graft-backed emission seam performs one bounded same-host receiver delivery attempt and still surfaces typed sender warnings when the receiver path is unavailable",
    ),
    SuiteRowSpec(
        id="AD11-AUTH-001",
        flow="update-member auth checks and infallible add-member projection are closed",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "update_member_rejects_caller_",
            ],
            [
                "rg",
                "-n",
                r"fn build_member_add_roster_record\(request: &AddMemberRequest\) -> RosterEntry",
                "crates/atm-core/src/team_admin/member_mutation.rs",
            ],
            [
                "rg",
                "-n",
                r"validate_update_member_caller\(",
                "crates/atm-core/src/team_admin/member_mutation.rs",
            ],
        ],
        pass_note="the promoted AD.9 auth and infallible findings are closed: update-member consumes caller context materially, and add-member projection no longer pretends to fail",
    ),
    SuiteRowSpec(
        id="AD11-READINESS-001",
        flow="phase-ad readiness and boundary artifacts fail closed",
        commands=[
            [sys.executable, "scripts/validate_release.py", "phase-ad-readiness"],
        ],
        pass_note="Phase AD readiness records, smoke artifacts, and MessageReceivedHookEmitter boundary inventory are all present and wired into the retained validation gate",
    ),
    SuiteRowSpec(
        id="AD17-ULID-001",
        flow="retained ATM message identity stays ULID-only on the accepted line",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "schema::inbox_message::tests::atm_message_id_parses_from_ulid_string",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "schema::inbox_message::tests::atm_message_id_timestamp_matches_derived_timestamp",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "send::tests::sqlite_failure_for_claude_preserves_original_and_companion_error_payloads",
                "--",
                "--exact",
            ],
        ],
        pass_note="ULID-only message identity remains enforced in the retained SQLite mailbox state",
    ),
    SuiteRowSpec(
        id="AD17-READ-001",
        flow="read mutation and contains filtering stay self-consistent on the durable store-backed path",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "--test",
                "mailbox_locking",
                "read_store_backed_display_mutation_ignores_mailbox_file_lock",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "read::tests::actionable_selection_preserves_parent_context_for_add_details",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "read::tests::actionable_selection_does_not_preserve_parent_context_for_supersede",
                "--",
                "--exact",
            ],
        ],
        pass_note="read mutation still reports the post-mutation state and contains filtering still sees the durable full-body projection",
    ),
    SuiteRowSpec(
        id="AD17-CI-001",
        flow="windows CI retains the explicit atm-daemon lane on the accepted line",
        commands=[
            [
                "rg",
                "-n",
                "Run atm-daemon tests",
                ".github/workflows/ci.yml",
            ],
            [
                "python3",
                "-c",
                "from pathlib import Path; data = Path('.github/workflows/ci.yml').read_text(encoding='utf-8'); raise SystemExit(1 if \"if: runner.os != 'Windows'\" in data else 0)",
            ],
        ],
        pass_note="the explicit atm-daemon CI lane remains present and the Windows skip guard is absent",
    ),
    SuiteRowSpec(
        id="AD18-RUNTIME-ROOT-001",
        flow="shared-host raw CLI bootstrap reuses a single daemon and keeps runtime state under the accepted ATM_HOME root",
        commands=[
            [sys.executable, "scripts/smoke/run_thorough_shared_host.py"],
        ],
        pass_note="shared-host smoke proves multi-workspace raw CLI bootstrap reuses one daemon, preserves team isolation, and keeps runtime ownership under the accepted ATM_HOME root",
    ),
    SuiteRowSpec(
        id="AD19-READ-OUTPUT-001",
        flow="read mutation returns the message it actually mutated together with post-mutation bucket counts",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "--test",
                "mailbox_locking",
                "read_unread_output_stays_consistent_with_the_mutated_message",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "--test",
                "mailbox_locking",
                "ack_persists_read_state_and_acknowledged_timestamp",
                "--",
                "--exact",
            ],
        ],
        pass_note="read returns the durable message it actually mutated, reports post-mutation unread counts, and leaves ack mutation semantics intact",
    ),
    SuiteRowSpec(
        id="AD20-READ-CONTAINS-001",
        flow="metadata-backed contains stays full-body correct while keeping durable-body reload bounded",
        commands=[
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "--test",
                "mailbox_locking",
                "read_contains_matches_summary_only_and_body_only_on_store_backed_path",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "--test",
                "mailbox_locking",
                "list_contains_matches_body_only_on_store_backed_path",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "read::tests::metadata_backed_read_contains_fetches_durable_body_when_summary_misses",
                "--",
                "--exact",
            ],
            [
                "cargo",
                "test",
                "-p",
                "agent-team-mail-core",
                "list::tests::metadata_backed_contains_fetches_durable_body_only_for_surviving_summary_miss_rows",
                "--",
                "--exact",
            ],
        ],
        pass_note="metadata-backed contains stays full-body correct and only reloads durable body for surviving summary-miss candidates",
    ),
    *POST_SEND_ROWS,
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Phase AD thorough smoke runner")
    parser.add_argument("--write-artifacts", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    payload = run_suite("thorough", THOROUGH_ROWS, write_artifacts=args.write_artifacts)
    return 0 if payload["status"] == "passed" else 1


if __name__ == "__main__":
    raise SystemExit(main())
