[package]
name = "atm-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "ATM concrete runtime composition crate."
repository.workspace = true
homepage.workspace = true

[lib]
name = "atm_runtime"

[dependencies]
atm-core.workspace = true
atm-storage.workspace = true
async-trait.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
atm-runtime-test-support = { path = "../atm-runtime-test-support" }
atm-storage = { path = "../atm-storage", version = "1.4.6", features = ["test-utils"] }
serde_json.workspace = true
