from __future__ import annotations

from pathlib import Path
import subprocess
import unittest


ROOT = Path(__file__).resolve().parents[2]
RENDERED_SUFFIXES = {".html", ".xhtml"}
# Regenerated by `just reports-index` / `just procedures`; both have their own --check gates.
# send-message-benchmark.json is the latest-campaign discovery envelope that
# `just benchmark-report` rewrites (and benchmark_publish.py stages) on every campaign.
GENERATED_FILES = {
    "site/reports/index.html",
    "site/reports/procedures/manifest.json",
    "site/reports/send-message-benchmark.json",
}


def is_allowed_report_change(status: str, path: str) -> bool:
    """Evidence under site/reports is add-only; pages are regenerable; exact renames keep evidence intact."""
    if status == "A" or path in GENERATED_FILES:
        return True
    if status.startswith("R"):
        # A moved payload must stay byte-identical (BB.8 moved the colima runs into
        # site/reports/integration/); a rename with edits is an evidence edit.
        return status == "R100"
    name = Path(path)
    # Rand's 2026-09-13 directive permits the site-links gate to repair links in
    # rendered pages, and a rendered page or discovery envelope may be replaced
    # when its evidence moves; runner-written evidence itself is never edited or removed.
    return status in {"M", "D"} and (name.suffix.lower() in RENDERED_SUFFIXES or (status == "D" and name.name == "smoke.envelope.json"))


class SiteReportsDiffTests(unittest.TestCase):
    def test_site_reports_diff_is_generated_only(self):
        base = subprocess.check_output(["git", "merge-base", "origin/develop", "HEAD"], cwd=ROOT, text=True).strip()
        result = subprocess.run(
            ["git", "diff", "--name-status", "-M100%", base, "--", "site/reports"],
            cwd=ROOT, capture_output=True, text=True, check=True,
        )
        changed = [tuple(line.split("\t", 1)) for line in result.stdout.splitlines() if line]
        violations = [pair for pair in changed if not is_allowed_report_change(*pair)]
        self.assertEqual(violations, [])

    def test_exact_rename_keeps_evidence_but_edits_and_deletions_do_not(self):
        payload = "site/reports/integration/colima/20260912T111004Z/steps/01-hermes-skills/step.json"
        self.assertTrue(is_allowed_report_change("R100", payload))
        self.assertFalse(is_allowed_report_change("R087", payload))
        self.assertFalse(is_allowed_report_change("M", payload))
        self.assertFalse(is_allowed_report_change("D", payload))
        self.assertFalse(is_allowed_report_change("D", "site/reports/integration/colima/20260912T111004Z.envelope.json"))
        self.assertTrue(is_allowed_report_change("D", "site/reports/smoke/linux/hermes-testbed/x/smoke.envelope.json"))
        self.assertTrue(is_allowed_report_change("D", "site/reports/bb4-task-start/x/index.html"))
        self.assertTrue(is_allowed_report_change("M", "site/reports/procedures/smoke-fast/index.html"))
        self.assertTrue(is_allowed_report_change("A", payload))
        self.assertTrue(is_allowed_report_change("M", "site/reports/procedures/manifest.json"))
        self.assertTrue(is_allowed_report_change("M", "site/reports/send-message-benchmark.json"))
        self.assertFalse(is_allowed_report_change("M", "site/reports/send-message-benchmark/20260914T200908Z-m5-atmbench-tcp.json"))


if __name__ == "__main__":
    unittest.main()
