[package]
name = "atm-architecture"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dev-dependencies]
cargo_metadata.workspace = true
serde.workspace = true
syn = { version = "2", features = ["full", "visit"] }
toml = "0.8"
